### ISSUE TITLE
Cannot find module '@angular/service-worker/src/low_level'

### ISSUE THREAD

**Issue by carlosdubus** [maciejtreder/ng-toolkit#639]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[x] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

After upgrading from angular 7 to 8 I'm getting the following. I tried reinstalling @ng-toolkit/pwa and @angular/service-worker to no avail.

Any ideas?

<pre><code>ERROR in ../node_modules/@ng-toolkit/pwa/ngt-pwa/sw-update-server.mock.service.d.ts:2:60 - error TS2307: Cannot find module '@angular/service-worker/src/low_level'.

2 import { UpdateActivatedEvent, UpdateAvailableEvent } from '@angular/service-worker/src/low_level';</code></pre>

## Environment

<pre><code>
Angular CLI: 8.1.0
Node: 10.15.3
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.0
@angular-devkit/build-angular              0.801.0
@angular-devkit/build-optimizer            0.801.0
@angular-devkit/build-webpack              0.801.0
@angular-devkit/core                       7.3.9
@angular-devkit/schematics                 7.3.9
@angular/.DS_Store                         <error>
@angular/cdk                               7.3.2
@angular/flex-layout                       7.0.0-beta.23
@angular/http                              7.2.5
@angular/material                          7.3.0
@angular/pwa                               0.12.4
@ngtools/webpack                           8.1.0
@nguniversal/common                        7.1.1
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.0
@schematics/angular                        7.3.9
@schematics/update                         0.801.0
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.35.2
</code></pre>

**Comment by carlosdubus** [comment]
To fix this I had to update this file:

./node_modules/@ng-toolkit/pwa/ngt-pwa/sw-update-server.mock.service.d.ts

From this:

```
import { Observable } from 'rxjs';
import { UpdateActivatedEvent, UpdateAvailableEvent } from '@angular/service-worker/src/low_level';
export declare class SwUpdateServerMock {
    available: Observable<UpdateAvailableEvent>;
    activated: Observable<UpdateActivatedEvent>;
    isEnabled: boolean;
    checkForUpdate(): Promise<void>;
    activateUpdate(): Promise<void>;
}

```

to this:
```
import { Observable } from 'rxjs';
// import { UpdateActivatedEvent, any } from '@angular/service-worker/src/low_level';
export declare class SwUpdateServerMock {
    available: Observable<any>;
    activated: Observable<any>;
    isEnabled: boolean;
    checkForUpdate(): Promise<void>;
    activateUpdate(): Promise<void>;
}
```

**Comment by pauloantonelli** [comment]
> To fix this I had to update this file:
> 
> ./node_modules/@ng-toolkit/pwa/ngt-pwa/sw-update-server.mock.service.d.ts
> 
> From this:
> 
> ```
> import { Observable } from 'rxjs';
> import { UpdateActivatedEvent, UpdateAvailableEvent } from '@angular/service-worker/src/low_level';
> export declare class SwUpdateServerMock {
>     available: Observable<UpdateAvailableEvent>;
>     activated: Observable<UpdateActivatedEvent>;
>     isEnabled: boolean;
>     checkForUpdate(): Promise<void>;
>     activateUpdate(): Promise<void>;
> }
> ```
> 
> to this:
> 
> ```
> import { Observable } from 'rxjs';
> // import { UpdateActivatedEvent, any } from '@angular/service-worker/src/low_level';
> export declare class SwUpdateServerMock {
>     available: Observable<any>;
>     activated: Observable<any>;
>     isEnabled: boolean;
>     checkForUpdate(): Promise<void>;
>     activateUpdate(): Promise<void>;
> }
> ```
> 
> I'm not sure why the mock classes are being imported in my project. I already made sure the dependency is not in devDependencies just in case. Any ideas?

Thanks friend! Your solution work fine for me!!

**Comment by KingDarBoja** [comment]
Need to take a look at those files to check what is going on. This is a reminder for myself.

**Comment by KingDarBoja** [comment]
Closing now as this should be fixed on recent releases.
